name: GitHub Snake Game

on:
  # SE PROGRAMA LA EJECUCION DIARIA A MEDIANOCHE UTC
  schedule:
    - cron: "0 0 * * *"
  # PERMITE EJECUTAR MANUALMENTE EL WORKFLOW
  workflow_dispatch:
  # SE EJECUTA CUANDO HAY UN PUSH A LA RAMA PRINCIPAL
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # COMENTARIOS A TENER EN CUENTA
      # CLONA EL REPOSITORIO
      - name: Checkout Repository
        uses: actions/checkout@v3

      # GENERA LA ANIMACION DEL SNAKE
      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: wsxdev
          outputs: |
            dist/github-snake.svg?palette=github-light&color_snake=black
            dist/github-snake-dark.svg?palette=github-dark&color_snake=white
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # SE PUBLICA LOS ARCHIVOS GENERADOS EN LA RAMA "OUTPUT"
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update snake animation [skip ci]"